trigger:
- main

stages:
  - stage: 
    displayName: 
    pool: adopool25
    variables:
      build configuration: "Reease"
      build platform: "any cpu"
    jobs:
      - job: adojob
        displayName: ado_job 
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              projects: 'WebApplication1/WebApplication1.sln'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: 'WebApplication1/WebApplication1/WebApplication1.csproj'
              arguments: '--configuration $(BuildConfiguration)'
          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              publishWebProjects: true
              arguments: '--configuration $(BuildConfiguration) --output $(BuildStagingConfiguration)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: 
    displayName: 
    pool: adopool25
    jobs:
      - deployment: 
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: IISWebAppManagementOnMachineGroup@0
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'CreateOrUpdateWebsite'
                    WebsiteName: 'clientwebapp'
                    WebsitePhysicalPath: 'D:\clientartifacts'
                    WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
                    CreateOrUpdateAppPoolForWebsite: true
                    AppPoolNameForWebsite: 'clientappplan'
                    DotNetVersionForWebsite: 'v4.0'
                    PipeLineModeForWebsite: 'Integrated'
                    AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
                - task: IISWebAppDeploymentOnMachineGroup@0
                  inputs:
                    WebSiteName: 'clientwebapp'
                    Package: '$(System.DefaultWorkingDirectory)\**\*.zip'
                
  #             - task: AzureRmWebAppDeployment@5
  #               inputs:
  #                 ConnectionType: 'AzureRM'
  #                 azureSubscription: 'serviccon25'
  #                 appType: 'webApp'
  #                 WebAppName: 'webapp25'
  #                 packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
