trigger:
- main

stages:
  - stage:  'build_ci'
    displayName: CI
    pool: vmpool
    variables:
      build configuration: "Release"
      build platform: "any cpu"

    jobs:
      - job: 'build_job'
        displayName: build job
        steps:
              
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: 'WebApplication1/WebApplication1.sln'
            feedsToUse: 'select'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: 'WebApplication1/WebApplication1/WebApplication1.csproj'
            arguments: '--configuration $(BuildConfiguration)'
        - task: DotNetCoreCLI@2
          displayName: Publish
          inputs:
            command: publish
            publishWebProjects: True
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
            zipAfterPublish: True
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
          condition: succeededOrFailed()

            
  - stage: 
    displayName: cdpipeline
    pool: vmpool
    jobs:
      - deployment:
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: IISWebAppManagementOnMachineGroup@0
                  inputs:
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'CreateOrUpdateWebsite'
                    WebsiteName: 'clientwebapp'
                    WebsitePhysicalPath: 'D:\webapp'
                    WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
                    CreateOrUpdateAppPoolForWebsite: true
                    AppPoolNameForWebsite: 'clientappplan'
                    DotNetVersionForWebsite: 'v4.0'
                    PipeLineModeForWebsite: 'Integrated'
                    AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
                - task: IISWebAppDeploymentOnMachineGroup@0
                  inputs:
                    WebSiteName: 'clientwebapp'
                    Package: '$(pipeline.workspace)\**\*.zip'
            